- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/network_plugin?
  value: /var/vcap/packages/netplugin-shim/bin/garden-plugin

- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/network_plugin_extra_args?
  value:
    - "--socket"
    - "/var/vcap/data/garden/sockets/networker.sock"
